### ISSUE TITLE
Extract error when scanning datasets - float argument is cftime.datetime

### ISSUE THREAD

**Issue by ellesmith88** [roocs/dachar#55]
* dachar version:
* Python version:
* Operating System:

### Description

`float() argument must be a string or a number, not 'cftime._cftime.DatetimeGregorian` (c3s-cmip5)

`float() argument must be a string or a number, not 'cftime._cftime.DatetimeProlepticGregorian` (c3s-cordex)

**Comment by ellesmith88** [comment]
In character.py `get_coord_type` returns None for the time coord in some datasets so time doesn't get given coord_type=time in `get_coords` and so code attempts to calculate min and max as a non-time coord. 

Returns none  in `get_coord_type` because coord.attrs only returns {'bounds': 'time_bnds'} so it doesn’t have a standard name.

Could be fixed by changing check of time from `if coord_type == 'time':` to `if name == 'time':`

**Comment by agstephens** [comment]
I think we need to maintain: `if coord_type == 'time'` - but we might need to increase the number of ways in which we try to identify the "time" coordinate. 

@ellesmith88 Please look at the CF Conventions document to check what the rules are on how to specify a `time` coordinate variable.

**Comment by ellesmith88** [comment]
The CF conventions document says:

A time coordinate is identifiable from its units string alone.
Optionally, the time coordinate may be indicated additionally by providing the standard_name attribute with an appropriate value, and/or the axis attribute with the value T.

In the datasets with this error the time coordinate doesn't have any units or a standard name, so this seems like an issue that needs to be fixed with these datasets, rather than changing the code to work around this. @agstephens what do you think?

**Comment by agstephens** [comment]
@ellesmith88 I agree. This is one that we should report. 

Please let Ruth know which datasets are affected.

**Comment by ellesmith88** [comment]
Ruth came back and said 'The missing time standard name is only a warning so we have allowed this through as allowable error.' 

Looking into the time units, these exist in the dataset but are removed by xarray when it decodes the time.

**Comment by agstephens** [comment]
@ellesmith88 : I think there is a way to get to the units, I think they are hidden in some metadata object attached to the coordinate variable. Please have a dig and see if you can find them.
