### ISSUE TITLE
Set up ElasticSearch indexes for character, analysis, fix proposals, fix

### ISSUE THREAD

**Issue by agstephens** [roocs/dachar#63]
Work plan:

 1. Define whether we need an index "mapping"
 2. Write code to create indexes
 3. Manage access control:
   - write with access token
   - otherwise: read-only
 4. Write ElasticSearch handlers in the JsonStore class.
 5. Populate with some content
 6. Create some minimal documentation for querying

**Comment by agstephens** [comment]
Names for indexes:
 - roocs-char-YYYYMMDD  (Alias: roocs-char)
 - roocs-???

**Comment by ellesmith88** [comment]
Aliases easy to create using python put_alias() method
